network:
  ethernets:
    enp2s0f0:
      addresses: [134.117.92.171/24]
      gateway4: 134.117.92.1
      nameservers:
          addresses: [134.117.1.11, 134.117.242.35]
    enp2s0f1:
      addresses:
        - 10.43.1.131/24
      routes:
      - to: 10.43.1.121/32
        via: 10.43.1.131
    enp2s0f2:
      addresses:
        - 10.43.1.132/24
      routes:
      - to: 10.43.1.112/32
        via: 10.43.1.132
      - to: 10.43.1.10/32
        via: 10.43.1.112
      - to: 10.43.1.142/32
        via: 10.43.1.112

        #enp2s0f3:
        #  addresses:
        #  routes:
    #  addresses:
    #    - 10.43.1.133/24
    #  routes:
    #  - to: 10.43.1.20/32
    #    via: 10.43.1.133
  bridges:
    br1:
      interfaces: []
      addresses: [192.168.1.2/24]
  version: 2
