network:
  ethernets:
    enp2s0f0:
      addresses: [134.117.92.243/24]
      gateway4: 134.117.92.1
      nameservers:
          addresses: [134.117.1.11, 134.117.242.35]
      routes:
        - to: 172.17.0.0/16
          via: 10.43.1.20
  version: 2
